server.port=${SERVER_PORT:8888}
spring.task.execution.pool.core-size=10
spring.task.execution.pool.max-size=50
spring.task.execution.pool.queue-capacity=1000
spring.mvc.async.request-timeout=60000
server.connection-timeout=10000
# server.connection-timeout=1800000 # Set to 60 seconds
server.servlet.context-path=${SERVER_CONTEXT_PATH:/api/v1/admin}
spring.application.name=admin
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#---spring.jpa.show-sql---: true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#---jwt---
security.jwt.secret-key=${JWT_SECRET}
# 1d in millisecond
security.jwt.expiration-time=${JWT_EXPIRATION:86400000}
