export { default as ProductBreadcrumbComponent } from './product-breadcrumb.component'
export { default as ProductCommentComponent } from './product-comment.component'
export { default as ProductListComponent } from './product-list.component'
export { default as ProductShopComponent } from './product-shop.component'
export { default as ProductDetailComponent } from './product-detail.component'
export { default as ProductOverviewComponent } from './product-overview.component'
