-- Write your SQL migration here
START TRANSACTION;

CREATE TABLE posts (
  "id" bigint NOT NULL,
  "shop_id" bigint DEFAULT NULL,
  "cat_id" int DEFAULT NULL,
  "video_id" varchar(255) DEFAULT NULL,
  "promotion_id" bigint DEFAULT NULL,
  "discount_id" bigint DEFAULT NULL,
  "currency" varchar(255) DEFAULT NULL,
  "stock" int DEFAULT NULL,
  "status" int DEFAULT NULL,
  "sold" int DEFAULT NULL,
  "liked_count" int DEFAULT NULL,
  "cmt_count" int DEFAULT NULL,
  "discount" varchar(255) DEFAULT NULL,
  "raw_discount" int DEFAULT NULL,
  "size_chart" varchar(255) DEFAULT NULL,
  "shop_name" varchar(255) DEFAULT NULL,
  "description" varchar(255) DEFAULT NULL,
  "transparent_background_image" varchar(255) DEFAULT NULL,
  "images" varchar(1000) DEFAULT NULL,
  "view_count" int DEFAULT NULL,
  "name" varchar(1000) DEFAULT NULL,
  "image" varchar(1000) DEFAULT NULL,
  "price" int DEFAULT NULL,
  "price_min" int DEFAULT NULL,
  "price_max" int DEFAULT NULL,
  "historical_sold" int DEFAULT NULL,
  "price_before_discount" int DEFAULT NULL,
  "price_min_before_discount" int DEFAULT NULL,
  "price_max_before_discount" int DEFAULT NULL,
  "shop_rating" FLOAT DEFAULT NULL,
  "filename" varchar(255) DEFAULT NULL,
  "liked" bit(1) DEFAULT NULL,
  "is_official_shop" bit(1) DEFAULT NULL,
  "is_service_by_shop" bit(1) DEFAULT NULL,
  "show_free_shipping" bit(1) DEFAULT NULL,
  "variations" json DEFAULT NULL,
  "is_active" tinyint(1) NOT NULL DEFAULT '0',
  "metadata" json DEFAULT NULL,
  "created_by" int DEFAULT NULL,
	"deleted_by" int DEFAULT NULL,
	"updated_by" int DEFAULT NULL,
  "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted_at" timestamp NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
COMMIT